export interface IProduct {
  _id:number;
  id:string;
  status:string;
  price:number;
  title:string;
  description:string;
  rating:number;
  stock:number;
  retailer_id:number;
  quantity:number;
  brand:string;
  category:string;
  thumbnail:string;
  images:string[];
  img:string;
  name:string;
  email:string;
}
